sudo: false
language: node_js
node_js:
  - "12"
  - "10"
  - "8"

cache:
  directories:
    - node_modules
notifications:
  email: false

jobs:
  include:
    - stage: lint
      node_js: "10"
      script: npm run lint
    - stage: test
      script: npm run tap
    - stage: npm release
      node_js: "10"
      script: skip
      after_success:
        - npm i -g semantic-release @semantic-release/exec && semantic-release
branches:
  only:
    - master
